# Generated by Django 4.1.3 on 2024-05-26 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RealEstateapp', '0004_property_city_property_state'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='seller',
        ),
        migrations.RemoveField(
            model_name='property',
            name='title',
        ),
        migrations.AddField(
            model_name='property',
            name='image',
            field=models.ImageField(default='', upload_to='static/'),
        ),
        migrations.AddField(
            model_name='property',
            name='property_name',
            field=models.CharField(default='', max_length=45),
        ),
        migrations.AddField(
            model_name='property',
            name='seller_name',
            field=models.CharField(default='', max_length=45),
        ),
        migrations.AlterField(
            model_name='property',
            name='area_sq_feet',
            field=models.CharField(default='', max_length=12),
        ),
        migrations.AlterField(
            model_name='property',
            name='description',
            field=models.CharField(default='', max_length=200),
        ),
    ]
