# Generated by Django 4.1.3 on 2024-05-26 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RealEstateapp', '0005_remove_property_seller_remove_property_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='email_id',
            field=models.EmailField(default='', max_length=254, unique=True),
        ),
        migrations.AddField(
            model_name='property',
            name='mobile_no',
            field=models.CharField(default='', max_length=12),
        ),
        migrations.AlterField(
            model_name='user',
            name='email_id',
            field=models.EmailField(default='', max_length=254, unique=True),
        ),
    ]
