# Generated by Django 4.1.3 on 2024-05-26 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RealEstateapp', '0006_property_email_id_property_mobile_no_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stateid', models.IntegerField()),
                ('cityid', models.IntegerField()),
                ('cityname', models.CharField(default='', max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='States',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stateid', models.IntegerField()),
                ('statename', models.CharField(default='', max_length=45)),
            ],
        ),
    ]
